
 
### Get products
Get http://localhost:3000/api/product?limit=10&skip=0 HTTP/1.1

### Post product
Post http://localhost:3000/api/product HTTP/1.1

{
  "name": "Best Product",
  "description":"This is the product description.",
  "readyDate": "2018-05-10",
  "expiryDate": "2022-05-10",
  "basePrice": "5000",
  "quantity": 10,
  "unit": "kg",
  "images": ["https://avatars0.githubusercontent.com/u/1500684?s=460&v=4"],
  "tag": ["First"],
  "user": "60e429574aff4402004075e0"
}



###
Get http://localhost:3000/api/product/bid HTTP/1.1


###
POST http://localhost:3000/api/product/bid HTTP/1.1

{
  "product": "60e3f8978067da3638c642c4",
  "title": "Product Bid Thus",
  "amount": 500
}